server:
  port: 9999
zuul:
  routes:
    offer:
      path: /offer/**
      url: http://54.242.100.85:1001/api/v1
    shoe:
      path: /products/**
      url: http://54.242.100.85:1002/api/v1
    wishlist:
      path: /wishlist/**
      url: http://54.242.100.85:1003
    cart:
      path: /cart/**
      url: http://54.242.100.85:1004/api/v1
